### PR TITLE
A few lines to add in /event.php in order to use navigation-bar in theme/extcal/templates/extcal_event.tpl

### PR DESCRIPTION
**Pull request by Tzvook**
to add after line 207:

`// TZV //
//mb missing for xBootstrap templates by Tzvook
$lang = [
    'start'      => _MD_EXTCAL_START,
    'end'        => _MD_EXTCAL_END,
    'calmonth'   => _MD_EXTCAL_NAV_CALMONTH,
    'calweek'    => _MD_EXTCAL_NAV_CALWEEK,
    'year'       => _MD_EXTCAL_NAV_YEAR,
    'month'      => _MD_EXTCAL_NAV_MONTH,
    'week'       => _MD_EXTCAL_NAV_WEEK,
    'day'        => _MD_EXTCAL_NAV_DAY,
    'agendaweek' => _MD_EXTCAL_NAV_AGENDA_WEEK,
    'agendaday'  => _MD_EXTCAL_NAV_AGENDA_DAY,
    'search'     => _MD_EXTCAL_NAV_SEARCH,
    'newevent'   => _MD_EXTCAL_NAV_NEW_EVENT,
];
// Assigning language data to the template
$xoopsTpl->assign('lang', $lang);
$xoopsTpl->assign('view', 'event');`

-----------------------------------

only then this will work
`<{include file="db:extcal_navbar.tpl"}>`

### CODE REVIEW

**Comment by mambax7** [comment]
Thank you so much! I'll be working on it this week.

**Comment by Tzvook** [comment]
Hi Mamba 
I saw you work on the module .. so here is 2 feature request :
1. In the "location page" it will quite logical to list all (future ? ) location events. 
2. in the "location page" the description don't get HTML ( I worked around it via SMARTY, but it's a bug that needs to be fixed ... )

**Comment by alain01** [comment]
XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.16
mySQL Version | 8.0.16

This Pull request

===========
Page /admin.php 

Warning: Declaration of XoopsModules/Extcal/LocationHandler::getAll(?CriteriaElement $criteria = NULL, $fields = NULL, $asObject = true, $id_as_key = true) should be compatible with & XoopsPersistableObjectHandler::getAll(?CriteriaElement $criteria = NULL, $fields = NULL, $asObject = true, $id_as_key = true) in file /modules/extcal/class/LocationHandler.php line 86

**Comment by alain01** [comment]
page

**Comment by alain01** [comment]
TY ! 
Better, but another errors  :

Erreurs @ /modules/extcal/view_calendar-month.php
--
Inconnu: The each() function is deprecated. This message will be suppressed on further calls dans le fichier /modules/extcal/class/pear/Calendar/Calendar.php ligne 388
Avertissement: xoopsOption['template_main'] should be defined before including header.php dans le fichier /footer.php ligne 58

**Comment by alain01** [comment]
Strange way : 
in admin page, if i create an event with catégories
if i dont change settings in 
"View permission/Select categories that each group is allowed to view"
"Add Webmasters" to "cat1" "cat2" "cat3",
so,
If i want to edit it now 
- i click on the edit button :"/modules/extcal/admin/event.php?op=modify&event_id=2"
- frame "Edit event" is empty

**I need to go to the tab permission before, 
cause, for webmaster, the catégories is not coched by default**

Same problem
> B : clone event
> C : I cant see this event on the  /modules/extcal/view_calendar-month.php
> D : empty selected list
- /modules/extcal/view_calendar-month.php : list 3
- modules/extcal/view_calendar-week.php : list 4
- /modules/extcal/view_year.php : list 2
- /modules/extcal/view_month.php : list 3
- /modules/extcal/view_week.php : list 4
- /modules/extcal/view_day.php: list 4

All is ok if i change the permission (for webmaster)

**Comment by mambax7** [comment]
Because it's the sample data. 
If you create your own category and set the permissions, then it should work.

**Comment by alain01** [comment]
i 've created my own catégories, didnt use sample date

**Comment by mambax7** [comment]
Pear  library is behind and is not being updated frequently :(

**Comment by alain01** [comment]
I mean, by default, for each new catégorie,
group webmasters should be "view permission" : yes

**Comment by alain01** [comment]
ok, for 
Inconnu: The each() function is deprecated. This message will be suppressed on further calls dans le fichier /modules/extcal/class/pear/Calendar/Calendar.php ligne 388
it's done, T.Y.

but still : 
Avertissement: xoopsOption['template_main'] should be defined before including header.php dans le fichier /footer.php ligne 58

**Comment by alain01** [comment]
New Avertissement now on admin pages : 

Avertissement: Declaration of XoopsModules/Extcal/ExtcalPersistableObjectHandler::deleteAll(?CriteriaCompo $criteria = NULL, $force = true, $asObject = false) should be compatible with XoopsPersistableObjectHandler::deleteAll(?CriteriaElement $criteria = NULL, $force = true, $asObject = false) dans le fichier /modules/extcal/class/ExtcalPersistableObjectHandler.php ligne 734
--
Avertissement: Declaration of XoopsModules/Extcal/ExtcalPersistableObjectHandler::getList(?CriteriaCompo $criteria = NULL, $limit = 0, $start = 0) should be compatible with XoopsPersistableObjectHandler::getList(?CriteriaElement $criteria = NULL, $limit = 0, $start = 0) dans le fichier /modules/extcal/class/ExtcalPersistableObjectHandler.php ligne 734
Avertissement: Declaration of XoopsModules/Extcal/ExtcalPersistableObjectHandler::getCount(?CriteriaCompo $criteria = NULL) should be compatible with XoopsPersistableObjectHandler::getCount(?CriteriaElement $criteria = NULL) dans le fichier /modules/extcal/class/ExtcalPersistableObjectHandler.php ligne 734

**Comment by alain01** [comment]
so Fast !!!
ok now, no error in admin pages 

but 
(yes but ;-) )
when i update the module (tried 3 times)  i get this : 

Notification: Undefined index: file dans le fichier /modules/system/admin/modulesadmin/modulesadmin.php ligne 874
--
Avertissement: file(/modules/extcal/templates/): failed to open stream: No such file or directory dans le fichier /modules/system/admin/modulesadmin/modulesadmin.php ligne 546
Notification: Undefined index: description dans le fichier /modules/system/admin/modulesadmin/modulesadmin.php ligne 900

**Comment by alain01** [comment]
ok,
then I've desinstalled module then reinstalled.


Notification: Undefined index: file dans le fichier /modules/system/admin/modulesadmin/modulesadmin.php ligne 192
--
Avertissement: file(/modules/extcal/templates/): failed to open stream: No such file or directory dans le fichier /modules/system/admin/modulesadmin/modulesadmin.php ligne 546
Notification: Undefined index: file dans le fichier /modules/system/admin/modulesadmin/modulesadmin.php ligne 197
Notification: Undefined index: description dans le fichier /modules/system/admin/modulesadmin/modulesadmin.php ligne 198
Notification: Undefined index: file dans le fichier /modules/system/admin/modulesadmin/modulesadmin.php ligne 207
Avertissement: fopen(/themes/xswatch4/modules/system/): failed to open stream: No such file or directory dans le fichier /class/smarty/xoops_plugins/resource.db.php ligne 29
Avertissement: fread() expects parameter 1 to be resource, bool given dans le fichier /class/smarty/xoops_plugins/resource.db.php ligne 31
Avertissement: fclose() expects parameter 1 to be resource, bool given dans le fichier /class/smarty/xoops_plugins/resource.db.php ligne 32
Notification: Undefined index: file dans le fichier /modules/system/admin/modulesadmin/modulesadmin.php ligne 213

**Comment by alain01** [comment]
Nice ! 
now, default rights are ok:
The permission mask runs !
No error on installation/desinstallation
Just 1 error on front end user pages : Avertissement: xoopsOption['template_main'] should be defined before including header.php dans le fichier /footer.php ligne 58

Mamba, im' very happy to see the renaissance of a agenda module ! 
Great ! 

Just some questions : 
- I choosed icones for catégories but i ididnt see icones. I see color's catégorie, not icone's catégorie.
Dont understand why.
- Is it possible to add an event with multicategorie ?

I will work on cosmectics bugs and cosmetics add-on,
but all seems to be ok now.

**Comment by alain01** [comment]
Sample data : maybe data for 2020 ;-)

**Comment by alain01** [comment]
Editing block
_AM_TITLE
_AM_BADMIN

**Pull request merged**
